/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/items-table/items-table";
export namespace Components {
    interface ItemsTable {
        /**
          * Table header
         */
        "header": string;
        /**
          * Table items
         */
        "items": Array<Item>;
    }
}
declare global {
    interface HTMLItemsTableElement extends Components.ItemsTable, HTMLStencilElement {
    }
    var HTMLItemsTableElement: {
        prototype: HTMLItemsTableElement;
        new (): HTMLItemsTableElement;
    };
    interface HTMLElementTagNameMap {
        "items-table": HTMLItemsTableElement;
    }
}
declare namespace LocalJSX {
    interface ItemsTable {
        /**
          * Table header
         */
        "header"?: string;
        /**
          * Table items
         */
        "items"?: Array<Item>;
        "onItemClick"?: (event: CustomEvent<Item>) => void;
    }
    interface IntrinsicElements {
        "items-table": ItemsTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "items-table": LocalJSX.ItemsTable & JSXBase.HTMLAttributes<HTMLItemsTableElement>;
        }
    }
}
