inputs:
  source:
    description: 'Source'
runs:
  using: "composite"
  steps:
    - name: Install packages
      run: npm install
      shell: bash
      working-directory: ${{ inputs.source}}

    - name: Build component
      run: npm run build:prod
      shell: bash
      working-directory: ${{ inputs.source}}
