runs:
  using: "composite"
  steps:
    - name: Install packages
      run: npm install
      shell: bash

    # Build
    - name: Build component
      run: npm run build:prod
      shell: bash

    # Test
    - name: Test component
      run: npm run e2e
      shell: bash
