runs:
  using: "composite"
  steps:
    - name: Set Up
      uses: actions/setup-node@v1

    - name: Install packages
      run: npm install

    # Build
    - name: Build component
      run: npm run build:prod

    # Test
    - name: Test component
      run: npm run e2e
