default:
  image: node:latest

stages:
  - build
  - deploy

# caching for reuse
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build_pro:
  stage: build
  script:
    - npm install
    - npm run build
  only: ['master']
  artifacts:
    paths:
      - storybook/

deploy_S3:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 rm s3://microfrontends-applications-storybook --recursive
    - aws s3 cp storybook s3://microfrontends-applications-storybook --recursive

