/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardOverview {
        /**
          * Card amount
         */
        "amount": number;
        /**
          * Card last movement
         */
        "lastmovement": string;
        /**
          * Card limit
         */
        "limit": number;
        /**
          * locale
         */
        "locale": string;
        /**
          * Card number
         */
        "number": string;
        /**
          * Card type
         */
        "type": number;
    }
}
declare global {
    interface HTMLCardOverviewElement extends Components.CardOverview, HTMLStencilElement {
    }
    var HTMLCardOverviewElement: {
        prototype: HTMLCardOverviewElement;
        new (): HTMLCardOverviewElement;
    };
    interface HTMLElementTagNameMap {
        "card-overview": HTMLCardOverviewElement;
    }
}
declare namespace LocalJSX {
    interface CardOverview {
        /**
          * Card amount
         */
        "amount"?: number;
        /**
          * Card last movement
         */
        "lastmovement"?: string;
        /**
          * Card limit
         */
        "limit"?: number;
        /**
          * locale
         */
        "locale"?: string;
        /**
          * Card number
         */
        "number"?: string;
        /**
          * Card type
         */
        "type"?: number;
    }
    interface IntrinsicElements {
        "card-overview": CardOverview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-overview": LocalJSX.CardOverview & JSXBase.HTMLAttributes<HTMLCardOverviewElement>;
        }
    }
}
