name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Check changes
    outputs:
      run_mf-account-detail: ${{ steps.check_changes.outputs.run_mf-account-detail }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_changes
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == microfrontends/mf-account-detail/* ]]; then
              echo "::set-output name=run_mf-account-detail::true"
              break
            fi
          done < files.txt

  build_mf-account-detail:
    needs: check
    if: needs.check.outputs.run_mf-account-detail == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-account-detail
