name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Check changes
    outputs:
      run_mf-account-detail: ${{ steps.check_changes.outputs.run_mf-account-detail }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_changes
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == microfrontends/mf-account-detail/* ]]; then
              echo "::set-output name=run_mf-account-detail::true"
              break
            fi
            if [[ $file == microfrontends/mf-accounts-summary/* ]]; then
              echo "::set-output name=run_mf-accounts-summary::true"
              break
            fi
            if [[ $file == microfrontends/mf-card-detail/* ]]; then
              echo "::set-output name=run_mf-card-detail::true"
              break
            fi
            if [[ $file == microfrontends/mf-cards-summary/* ]]; then
              echo "::set-output name=run_mf-cards-summary::true"
              break
            fi
            if [[ $file == microfrontends/mf-balance-overview/* ]]; then
              echo "::set-output name=run_mf-balance-overview::true"
              break
            fi
            if [[ $file == microfrontends/mf-global-position/* ]]; then
              echo "::set-output name=run_mf-global-position::true"
              break
            fi
          done < files.txt

  build_mf-account-detail:
    needs: check
    if: needs.check.outputs.run_mf-account-detail == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-account-detail

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-account-detail  
  
  build_mf-accounts-summary:
    needs: check
    if: needs.check.outputs.run_mf-accounts-summary == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-accounts-summary

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-accounts-summary
        
  build_mf-card-detail:
    needs: check
    if: needs.check.outputs.run_mf-card-detail == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-card-detail

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-card-detail

  build_mf-cards-summary:
    needs: check
    if: needs.check.outputs.run_mf-cards-summary == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-cards-summary

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-cards-summary
        
  build_mf-balance-overview:
    needs: check
    if: needs.check.outputs.run_mf-balance-overview == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-balance-overview

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-balance-overview
        
        
  build_mf-global-position:
    needs: check
    if: needs.check.outputs.run_mf-global-position == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Microfrontend
        uses: ./.github/workflows/microfrontends
        with:
          source: ./microfrontends/mf-global-position

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.CLIENT_SECRET }}
          aws-region: eu-west-2

      - name: Deploy component
        run: npm run publish
        working-directory: ./microfrontends/mf-global-position
